sudo: true
dist: trusty
services:
- docker
env:
  global:
  - IMAGE_TAG=spiderpowa/bls-go-alpine
  - DOCKER_USER=spiderpowadeploy
  - secure: T4mkZzGofMqia/izUZAh1sPg8AD1ET7JWNagfRNZSClxkjjcgQp//LTZTuRVaaMhz5Bm3QwOLQ6IvtwUiS5fyaT49qLHXhx6PAY+w36g9lYJQkk02Kyy5sgyb9Kl1QzcoDmMOXKtQ1GiGa/BiOBcjhlWiuHi7l423RgVVu9fyhLKZBwGmyKnoTWVqZsx9XZVIizgZ1zXnIWJjTDkqZxDq0iXR++ZHmA+yhjn7qU8TNY6WGoewBvCpyIcW4Bkkinm4U7/pJN6w0QQcA3AQXbbymPmtH+CQeUqbK4WKpE1/0ugzAi68bijf7y9+W3eDwELwufYzbS2GPhvqe9J8kxeoNj5ej7St+Av08qJbKDyKCzF0pB2qpGgZl+MKFLYxmGmgHLlZZ8AO5aYkX/d4XJtS8ncnkvnTg0/D9FbVM9sWTdehI1xh65QXijFL5NC1IDsJDHfGsc/5KIEqwByRddBFwgqvbuLX9uZMnhFbMsOJSVBaRigsNvccY4CU8SD58kn6NJMFkTMQFxH93Qq89aEal7fWlCio0VGtRK7qK6izlTj95ryPC8tdNJIcgXB026hoVx9Zcjo5j26fXZR9hn3RqMY0AZwMKhvA8bLixrjtLDjrg3VphKmCrMaXH1q13EyoGSHCLwSklizfSqbYyqS+9t0PFpDQ3dZ4iIvsAbi3EA=
language: cpp
compiler:
- gcc
- clang
addons:
  apt:
    packages:
    - libgmp-dev
install:
- git clone --depth 1 https://github.com/herumi/mcl.git $TRAVIS_BUILD_DIR/../mcl
script:
- make -j3
- make test_ci DISABLE_THREAD_TEST=1
- make test_go
- env LD_LIBRARY_PATH=../mcl/lib bin/bls_c384_test.exe
- make clean && make -C ../mcl clean
- make -j3 MCL_USE_OPENSSL=0
- make test_ci DISABLE_THREAD_TEST=1 MCL_USE_OPENSSL=0
- docker build --tag "$IMAGE_TAG" . -f images/bls-go-alpine/Dockerfile --no-cache
before_deploy:
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
- git_commit="$(git rev-parse --short HEAD)"
- docker tag "$IMAGE_TAG" "${IMAGE_TAG}:${git_commit}"
- docker tag "$IMAGE_TAG" "${IMAGE_TAG}:latest"
deploy:
  provider: script
  script: docker push "${IMAGE_TAG}:latest" && docker push "${IMAGE_TAG}:${git_commit}"
  on:
    branch: dev
    condition: "$CC = gcc"
